name: Build and Run Rohan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔧 Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ python3 python3-pip
          pip3 install --upgrade pip
          pip3 install telebot  # Install required Python packages

      - name: 🚀 Compile C Program
        run: |
          g++ Rohan.c -o Rohan -pthread

      - name: 🎯 Run Executables
        run: |
          chmod +x Rohan || true  # Ensure Rohan is executable
          ./Rohan                 # Run the C program
          python3 Rohan.py         # Run the Python script
